export enum AppRoutes {
  HOME_SCREEN = '/',
  HOME_SCREEN_ = '/home',
  ABOUT_SCREEN = '/about',
  LIST_TOUR_SCREEN = '/tours',
  TOUR_DETAIL = `/tours/:id`,
  CHECK_OUT = '/tour_checkout',
  LIST_HOTEL_SCREEN = '/hotelS',
  HOTEL_DETAIL = `/hotel/:id`,
  HOTEL_CHECKOUT = '/hotel_checkout',
  PRIVACY_POLICY = '/privacy_policy',
  CONTACT_US = '/contact',
  THANKS = '/thanks',
  LOGIN = '/login',
  SIGN_UP = '/sign_up',
}