export * from './styles';
export * from './HotelDetailBody';
export * from './HotelDetailBodyDescription';
export * from './HotelDetailBodyReview';
export * from './HotelDetailTotalForm';
export * from './HotelDetailBodySelectRoom';
export * from './ModalSelectRoom';
export * from './DetailSelectRoomItem';
export * from './stylesTotalForm'